version: '3.8'
services:
  webapp:
    build:
      context: .
    restart: always
    ports:
    - 2020:5050 
    # volumes:
    #   - test-data:/usr/src/app/test-vol/
    
  db:
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'node_docker'
      MYSQL_HOST: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: ''
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    expose:
      - '3306'  
    volumes:
      - my-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      # - PMA_ARBITRARY=1
      # - PMA_HOS=db
      - PMA_PORT=3306
          
volumes:
  my-db:  
  